name: Lint

on:
  push:
    branches: [main]
    paths:
      - "dynabatch/**"
  pull_request:
    branches: [main]
    paths:
      - "dynabatch/**"
  workflow_dispatch:

jobs:
  black-isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - uses: actions/setup-python@v6.2.0
        with:
          python-version: "3.12"

      - name: Install linters
        run: pip install black isort

      - name: Black
        run: black --check .

      - name: isort
        run: isort --check-only .
